### ISSUE TITLE
Port to VSCode

### ISSUE THREAD

**Issue by akamud** [madskristensen/JavaScriptSnippetPack#1]
I thought about porting this to VSCode, so I want to know if you are interested in keeping this "officially" in your repo. 

This is very easy to port, I could do a PR with all the snippets, you would just have to arrange the publishing parts so it could stay under the same "umbrella".  

If you want to keep this repo VS-only, I'm planning on doing a port referencing your repo as inspiration.

What do you tink?

**Comment by madskristensen** [comment]
That's a great idea. Feel free to fork this project and create the VSCode plugin. Would be awesome!

**Comment by akamud** [comment]
Just finished the [port](https://github.com/akamud/vscode-javascript-snippet-pack).  

Thanks for your work on this extension :+1:
